package Lesson_6.util;

import Lesson_6.enums.CategoryType;

public class TestDataSet {
    public static final Long PRODUCT_SUGAR_ID = 2820l;
    public static final String PRODUCT_SUGAR_TITLE = "Sugar";
    public static final CategoryType PRODUCT_SUGAR_TYPE = CategoryType.FOOD;

    public static final Long PRODUCT_BANANAMAMA_ID = 8255l;
    public static final String PRODUCT_BANANAMAMA_TITLE = "Bananamama";
    public static final CategoryType PRODUCT_BANANAMAMA_TYPE = CategoryType.FOOD;
    // public static final int PRODUCT_BANANAMAMA_NEWPRICE = 80;
    public static final String PRODUCT_BANANAMAMA_TITLE_Big = "BANANAAAAAaaaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
}
